name: Secrets

run-name: ${{ github.actor }} is testing out GitHub Actions

on: [push]

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          cd ${{ github.workspace }}
          ls 
          pwd
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - shell: bash
        env: 
          SECRET_1: ${{ secrets.SECERET_1 }}

        run: | 
          echo "$SECRET_1"
